server.port: 9090

app:
  upstream:
    paypal:
      account: ${PAYPAL_ACCOUNT}
      clientId: ${PAYPAL_CLIENT_ID}
      secret: ${PAYPAL_SECRET}
      payerId: ${PAYPAL_PAYER_ID}
      uri: ${PAYPAL_URI:https://api.sandbox.paypal.com}
      resources:
        access_token: ${PAYPAL_RESOURCE_ACCESS_TOKEN:https://api.sandbox.paypal.com/v1/oauth2/token}
        execute: ${PAYPAL_RESOURCE_EXECUTE:/v1/payments/payment/:payment_id/execute}
        payment: ${PAYPAL_RESOURCE_PAYMENT:/v1/payments/payment}



spring:
  profiles: default

---

spring:
  profiles: test
app:
  upstream:
    paypal:
      account: payme@payme.comn
      clientId: myId
      secret: mySecret
---

spring:
  profiles: prod
